### ISSUE TITLE
Channel.close error

### ISSUE THREAD

**Issue by tyrylu** [sozu-proxy/lapin#215]
In Lapin 0.28.1, when i call channel.close(200, "Normal shutdown").wait() i get a connection error and then a invalid channel state error, the trace log (note that with the last line at the top e. g. output of journalctl -r) follows (only from when the close message was written to the channel):
```
Oct 12 05:10:20 hyperion worker[244381]: Error: InvalidChannelState(Error)
Oct 12 05:10:20 hyperion worker[244381]: [ERROR lapin::connection] Connection error
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::connection] will handle frame: Method(1, Channel(CloseOk(CloseOk)
))
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] read 12 bytes
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] wrote 0 bytes
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] io_loop do_run; can_read=true, can_write=true, has_data=
true
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] io_loop poll done
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] io_loop poll
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] io_loop run
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] io_loop do_run done; can_read=false, can_write=true, has
_data=true, status=Setup
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] io_loop send continue; can_read=false, can_write=true, h
as_data=true
Oct 12 05:10:20 hyperion worker[244381]: [TRACE lapin::io_loop] wrote 34 bytes
```

**Comment by Keruspe** [comment]
I guess you mean lapin 0.28.0?

Could you provide a minimal code sample to reproduce the problem?

**Comment by tyrylu** [comment]
Yes.

**Comment by tyrylu** [comment]
Yes. I'll to try to get some, but no idea how specific to the workload the think is.

**Comment by tyrylu** [comment]
Here's the minimal example (no logging configured there, but it predictably crashes), lapin in cargo.toml defined as lapin = "*":
```
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    println!("Connecting...");
    let conn = lapin::Connection::connect("amqp://app:FeelTheStreets@127.0.0.1/%2f", lapin::ConnectionProperties::default()).wait()?;
    println!("Connected.");
    let chan = conn.create_channel().wait()?;
    chan.basic_publish("", "test", lapin::options::BasicPublishOptions::default(), b"foo".to_vec(), lapin::BasicProperties::default()).wait()?;
    chan.close(200, "Normal shutdown").wait()?;
    conn.close(200, "Normal shutdown").wait()?;
    println!("Successfully closed.");
    Ok(())
}
```
The rabbitmq logs show nothing out of the ordinary, just an unexpected closing of a TCP connection for the app user.

**Comment by Keruspe** [comment]
So, what's the output of this one on your side?

Here I get
```
   Compiling lapin v0.28.0 (/home/keruspe/Projects/rust/lapin)
    Finished dev [unoptimized + debuginfo] target(s) in 2.12s
     Running `target/debug/examples/bug`
Connecting...
Connected.
Successfully closed.
```

**Comment by Keruspe** [comment]
My guess is that the "test" queue doesn't exist, so your connection gets closed by the server

**Comment by tyrylu** [comment]
Well, in the example it was a permissions issue for the app user which surfaced only after the call to wait of the close channel confirmation (i would expect it on the basic publish confirmation, but whatever...). No idea whether in the original example it is something related with the fact that the messages are being send in the span of hours (a long background tasks publishing few thousand messages in approximately three hours, then closing after itself), but i can't reproduce it in a minimal example. Someone got an idea why a channel state error could occur after a close_ok message? I'll probably print the channel and connection statuses along the task and report when it happens again (expecting tomorrow).

**Comment by tyrylu** [comment]
Not that i see anything unusual, but before the mentioned crash the connection and channel statuses (when printed the {:?} formatting specifier) are:
```
Oct 15 03:02:27 hyperion worker[911]: [INFO  server::background_tasks::area_db_update] Before closing, the connection st
atus is: ConnectionStatus { inner: RwLock { data: Inner { state: Connected, vhost: "/", username: "admin", blocked: fals
e } } }
Oct 15 03:02:27 hyperion worker[911]: [INFO  server::background_tasks::area_db_update] Before closing, the channel statu
s is: ChannelStatus { inner: RwLock { data: Inner { confirm: false, send_flow: true, state: Connected } } }
```

**Comment by tyrylu** [comment]
Alright, i managed to find what error causes the connection.set_error call, it's a Error::NotConnected error.

**Comment by Keruspe** [comment]
You might want to try your example with a couple of changes to see you you
get more intuitive results :

Call confirm_select after creating the channel
Call wait_for_confirms after you’re done publishing.

Basic publish doesn’t get any answer from the rabbitmq server unless
confirm extension is turned on so we cannot reliably catch such errors

**Comment by tyrylu** [comment]
I'll try to add these, they seem as a good idea anyway.

**Comment by tyrylu** [comment]
This version crashes pretty reliably:
```
use std::error::Error;
use lapin::options::ConfirmSelectOptions;

fn main() -> Result<(), Box<dyn Error>> {
    env_logger::init();
    println!("Connecting...");
    let conn = lapin::Connection::connect("amqp://someuserwhichcanpblish:HisPassword.@127.0.0.1/%2f", lapin::ConnectionProperties::default()).wait()?;
    println!("Connected.");
    let chan = conn.create_channel().wait()?;
    println!("Channel opened.");
    chan.confirm_select(ConfirmSelectOptions::default()).wait()?;
    println!("Confirmations requested.");
    for i in 0..1000 {
    chan.basic_publish("", "somewhere", lapin::options::BasicPublishOptions::default(), b"foo".to_vec(), lapin::BasicProperties::default()).wait()?;
    }
    for confirm in chan.wait_for_confirms().wait()? {
        if confirm.reply_code != 200 {
            println!("Non-200 confirmation: {:?}", confirm);
        }
    }
    println!("Messages published and confirmed.");
    println!("Conn state: {:?}", conn.status());
    println!("{:?}", chan.status());
    chan.close(200, "Normal shutdown").wait()?;
    println!("Channel closed.");
    conn.close(200, "Normal shutdown").wait()?;
    println!("Connection successfully closed.");
    Ok(())
}

```
What's weird is that it does not crash under gdb. It crashes on the chan.close line.

**Comment by Keruspe** [comment]
How does it crash? Do you get a coredump? Did you try with RUST_BACKTRACE=1
?
Doesn't seem to crash here:

```
Connecting...
Connected.
Channel opened.
Confirmations requested.
Messages published and confirmed.
Conn state: ConnectionStatus { inner: RwLock { data: Inner { state:
Connected, vhost: "/", username: "guest", blocked: false } } }
ChannelStatus { inner: RwLock { data: Inner { confirm: true, send_flow:
true, state: Connected } } }
Channel closed.
Connection successfully closed.
```

**Comment by tyrylu** [comment]
Just a 1 exit code with output:
```
Connecting...
Connected.
Channel opened.
Confirmations requested.
Messages published and confirmed.
Conn state: ConnectionStatus { inner: RwLock { data: Inner { state: Connected, vhost: "/", username: "admin", blocked: f
alse } } }
ChannelStatus { inner: RwLock { data: Inner { confirm: true, send_flow: true, state: Connected } } }
[2019-10-21T15:22:32Z ERROR lapin::connection] Connection error
Error: InvalidChannelState(Error)

```
If you think that a trace log would help, i can post it.

**Comment by Keruspe** [comment]
Might help, yes

**Comment by tyrylu** [comment]
Here it is, with a reduced message count to 1 (still the same error): https://gist.github.com/tyrylu/91d255625e485e12ebf57378e3aa4005
The handle frame entry after the close call is somewhat weird...

**Comment by Keruspe** [comment]
Ok, so what seems to be happening here (didn't dig in the code yet, that's just how I understand the logs):

- The message gets published
- We wait for confirmations but there are none pending
- We mark the message as "pending confirmation"
- We close the channel
- We receive the confirmation (Ack) which triggers an error as the channel is now closed

That would mean that there is an obvious race between the second and the third steps which should be in the opposite order

**Comment by Keruspe** [comment]
Could you try with my latest commit to confirm that?

Grepping for "confirm" in the trace logs should output this, in order:

```
[2019-10-22T07:50:01Z TRACE lapin::channel] Marked delivery 1 as pending confirmation
[2019-10-22T07:50:01Z TRACE lapin::channel] Waiting for pending confirms
[2019-10-22T07:50:01Z TRACE lapin::channel] Got confirmation for 1
```

**Comment by tyrylu** [comment]
Unfortunately, none of these showed up, just lonely:
[2019-10-22T08:37:09Z TRACE lapin::channel] No confirms to wait for

**Comment by Keruspe** [comment]
Could you retry now?

**Comment by tyrylu** [comment]
Unfortunately no changes, the trace output related to confirms is the same (yes, i did a cargo update).

**Comment by Keruspe** [comment]
Can you try once more to see if/when a new log appears. If it does appear but only after trying to wait for confirms, I know what the fix could be

**Comment by tyrylu** [comment]
After fixing the trace statement (a missing use declaration and a semicolon on the line before the trace), the results are that the channel confirms activated trace shows *before* the trace that sais the fact that there are no confirmations.

**Comment by Keruspe** [comment]
Heh, missed my amend before the push, sorry about that

**Comment by Keruspe** [comment]
Does this new trace log appear before sending the Basic.Publish frame or after?

**Comment by tyrylu** [comment]
Yes, it appears before the basic.publish message is written to the ioloop's buffer.

**Comment by Keruspe** [comment]
Can you post full logs with the trace I just added?
Something really fishy seems to be happening on your side and I just can't figure it out yet

**Comment by tyrylu** [comment]
Here you go: https://gist.github.com/tyrylu/951e21803f89c8d1c724640ffc4620c6

**Comment by Keruspe** [comment]
Ok, should be fixed by f68fd623473dea827a0a3cd7c7d1c62cff3469cb

Thanks a lot for the report and all the logs :)

Leaving it open until you confirm it's fixed

**Comment by tyrylu** [comment]
On this example it works, i'll post the results from the main application where it crashed in the first place.

**Comment by tyrylu** [comment]
Unfortunately, the fix did not fix the root cause of this issue. The logs of the task indicate that it received all confirmations from the server and during a channel close it crashed with a connection error just as before. I'll try to get some lapin trace logs there, but they might be somewhat larger.

**Comment by Keruspe** [comment]
Thanks for confirming the fix for the example.

In the meantime, I'm working on better error reporting in some situations (mostly for server errors), might help here.

0.29.0 should be out at some point today or tomorrow

**Comment by tyrylu** [comment]
No problem, yes, reporting can help, i hope. The already fixed issue was affecting the worker as well, so fixing this one was a definite improvement.

**Comment by fgt-moma** [comment]
I have the same problem with version 0.28.4, hope 0.29.0 come out soon.

**Comment by tyrylu** [comment]
Or at least the detailed logging promised so we can send the logs.

**Comment by Keruspe** [comment]
Sorry about that, I'm in a middle of some Errors rework for 0.29.0 and didn't have much time to work on it lately. Hope to release it soon too

**Comment by Keruspe** [comment]
Ok, so 0.29 will be released this week, should be better

**Comment by tyrylu** [comment]
Unfortunately is not, info log:
```
Mar 01 03:09:18 hyperion worker[796532]: Error: LapinError(InvalidChannelState(Connected))
Mar 01 03:09:18 hyperion worker[796532]: [ERROR lapin::connection] Connection error
Mar 01 03:09:18 hyperion worker[796532]: [INFO  server::background_tasks::area_db_update] Before closing, the connection status is: ConnectionStatus { inner: RwLock { data: Inner { state: Connected, vhost: "/", username: "admin", blocked: false } } }
Mar 01 03:09:18 hyperion worker[796532]: [INFO  server::background_tasks::area_db_update] Before closing, the channel status is: ChannelStatus { inner: RwLock { data: Inner { confirm: true, send_flow: true, state: Connected } } }
```
Would a trace log help?

**Comment by Keruspe** [comment]
Full code sample + trace logs would be appreciated yes, with latest lapin version

**Comment by tyrylu** [comment]
I can not reproduce it in anything smaller than this:
https://github.com/tyrylu/feel-the-streets/blob/master/server/src/background_tasks/area_db_update.rs
Most of the code is not lapin related, no idea whether the fact that the channel/underliing connection stays open for hours can have any effect. I'll post the trace log (or the relevant part, it would likely be massive) sometime tomorrow.

**Comment by tyrylu** [comment]
There's the part of the trace log after the confirmations were checked: https://gist.github.com/tyrylu/6c7d5847f4aab88458cee7855a3376d1
You don't want to read the whole thing as it has over 100 MiB in total.

**Comment by Keruspe** [comment]
Can you try again with 0.32.1?

**Comment by tyrylu** [comment]
I'll try.

**Comment by tyrylu** [comment]
Unfortunately, swapping a mutex instead of the lock did not fix the error. The error logs are the same, not sure whether the trace is as well, i'll post it, if you want.

**Comment by Keruspe** [comment]
Please post it, just in case

**Comment by Keruspe** [comment]
After thinking back of it it reminded me of another similar problem in old versions of lapin, wrt channel.close too and there was indeed part of the code path that was still subject to race conditions.
Fix is in 0.32.2 and will be in 0.33 shortly
