### ISSUE TITLE
A bogus publish stalls task waiting for confirm

### ISSUE THREAD

**Issue by jothan** [sozu-proxy/lapin#246]
I am in the process of connecting our app to RabbitMQ and I have started testing the latest lapin 0.35.2 code.

I am using a custom Rustls connection with code very similar to the example.

As a test, I am publishing to a bogus exchange that is forbidden:
```rust
let conn = custom_connect(uri, Default::default(), client_config).await.unwrap();
let chan = conn.create_channel().await.unwrap();
chan.confirm_select(Default::default()).await.unwrap();

tracing::error!("Before publish");
let r = chan.basic_publish("forbidden", "fakekey", Default::default(), Vec::new(), Default::default()).await;
tracing::error!("After publish: {:?}", r);
// stall here
let r = r.unwrap().await;
tracing::error!("Got confirm: {:?}", r);
```

This code does not panic and stalls between the "After publish" and "Got confirm" messages. Logging reveals that lapin receives the channel closure error.

Should the second confirmation future resolve with an error in this case ?

Looking forward to help you with testing,
Jonathan

**Comment by jothan** [comment]
Might be related to #245

**Comment by Keruspe** [comment]
Right, we definitely should propagate the error to the pending confirms

**Comment by Keruspe** [comment]
Fixed in 0.36.1

**Comment by jothan** [comment]
I'm still seeing this issue with the latest git.

2020-04-02 13:02:12-0400 ERROR themis_smtpd: After publish: Ok(PublisherConfirm { inner: Some(PinkySwear), returned_messages: ReturnedMessages { inner: Mutex { data: Inner { current_message: None, waiting_messages: [], messages: [], dropped_confirms: Promises { inner: Mutex { data: Inner { promises: [] } } }, pinkies: [] } } }, used: false })

I get an Ok from the first await after basic_publish, but I never see the "Got confirm" message after that second await.

**Comment by jothan** [comment]
Awesome, the latest code fixes this issue !

**Comment by Keruspe** [comment]
Thanks for confirming, at first I only fixed it when channels enters an error state, and not when it gets properly closed
